# Generated by Django 2.2 on 2020-09-13 21:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companymake', models.CharField(default='', max_length=50)),
                ('model_number', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('VIN_number', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('date_of_purchase', models.DateField(blank=True, default=datetime.datetime(2020, 9, 13, 21, 57, 59, 920652, tzinfo=utc), null=True)),
                ('date_of_last_service', models.DateField(blank=True, default=datetime.datetime(2020, 9, 13, 21, 57, 59, 920652, tzinfo=utc), null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
